name: Publish Images
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Images
        run: |
          current_working_dir=$(pwd)
          cd ~
          nmcp_dir=$(pwd)
          echo "Cloning and pre-building neuroglancer"
          git clone https://github.com/AllenNeuralDynamics/nmcp-neuroglancer.git
          cd nmcp-neuroglancer && git checkout debounce-resize
          npm install
          npm run build-package

          echo "Linking neuroglancer and publishing images"
          cd $current_working_dir
          npm install
          npm remove neuroglancer
          npm install --dev $nmcp_dir/nmcp-neuroglancer/dist/package
          npm list
          ls $nmcp_dir/nmcp-neuroglancer/dist/package
          chmod +x docker-entry.sh
          task release
